routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');



Route::any('/', function () {

    return view('auth.login');
});



Auth::routes();
//Route::get('/', 'usuario@ver');
Route::get('/JefeOp', function () {
    return view('Operaciones');
});

//Ruta usuario
Route::any('/Usuario','UserController@usuario');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::any('/ModificarUser/{id_user}', 'UserController@actualizar')->name ('modificar');
Route::resource('newUser', 'UserController');
//Ruta que sirve para mandar correo de verificacion de contraseña

Route::get('password/reset/{token?}', 'Auth\ForgotPasswordController@showLinkRequestForm');

Route::get('/marcas','PruebaController@compras');

Route::get('/home2', 'HomeController@index')->name('home3');
Route::get('/home3', 'HomeController@index')->name('home2');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/auth.register', 'usuario@verRoles');
Route::resource('/CrearProducto','Productos');
//Ruta que verifica el correo electronico
Auth::routes(['verify' => true]);
//Route::get('/modPro','proveedorController@mod')->name('modificarPro');
Route::any('/modPro/{id}','proveedorController@update')->name('modificarPro');
Route::any('/CrearProveedor','proveedorController@crear')->name('CrearPro');
Route::any('/lproveedor','proveedorController@index')->name('lproveedor');
Route::any('/BuscarPro','proveedorController@filtrado')->name('BuscarPro');
Route::any('/eliminarProv/{id}','proveedorController@destroy')->name('eliminarProv');
Route::any('/Crearmar','proveedorController@crearmarca')->name('Crearmar');
Route::get('/vermarca','proveedorController@vermarcas')->name('vermarca');
//Ruta para Proveedores

Route::get('/search','SearchController@search');
Route::resource('Provee','proveedorController',['only' => ['index', 'show']]);

//Controladores para Inventario
Route::any('/ModificarInv', 'InventoryController@listamodificar')->name('ModificarInv');
Route::any('/ModModificar/{id_Producto}','InventoryController@modal')->name ('modal');
Route::any('/BuscarInve','InventoryController@filtrado')->name('BuscarInve');
Route::get('/ModN/{id_Producto}', 'InventoryController@modalNuevo');
Route::any('/SucN/{id_sucursal}','InventoryController@almacen');
Route::resource('ModInv', 'InventoryController');


Route::any('/eliminarInv/{id_Producto}', 'InventoryController@eliminar')->name ('eliminar');
Route::get('/searchI','SearchController@search2');
//Terminan controladores para Inventario


    //rutas para obtener Reportes
    Route::any('/reporteU','BitacoraController@index')->name('reporteU');

    Route::any('/reportes','ReportesController@inventario');
    Route::any('/reporteUFecha','BitacoraController@busquedafecha')->name('reporteUFecha');
    Route::get('/graficaI', 'ReportesController@graficaI');

//Ruta para Proveedores
//Route::get('/modPro','proveedorController@mod')->name('modificarPro');




//Ruta para Proveedores



//Rutas para Pedidos (en realidad es Ordenes de compra)
Route::get('/verPedidos','PedidosController@VerPedidos')->name('verPedidos');
Route::any('/CrearPedido','PedidosController@CrearPedidos');
Route::get('/subP/{id}','PedidosController@byCategoria');
Route::get('/VerDetalles/{id}','PedidosController@verPedidosProductos');
Route::resource('ModPed', 'PedidosController');
Route::any('/borrarOrden','PedidosController@eliminar');
Route::get('/ProductosP/{id}', 'PedidosController@obtenerproductos');
Route::any('/AgregarP', 'PedidosController@agregarproductos');
Route::any('/AgregarS', 'PedidosController@agregarsucursal');
Route::get('/VerDetalle/{id}','PedidosController@verPedidosProducto');

//Rutas para PedidosReal
Route::get('/verPedidosReal','PedidosRealController@verPedidosReal')->name('verPedidosReal');
Route::resource('ModPedReal', 'PedidosRealController');
Route::any('/BuscarPed','PedidosRealController@BuscarPed')->name('BuscarPed');
Route::get('/VerDetalles2/{id}','PedidosRealController@verPedidosProductos');

//Rutas Productos

/////////////Vistas Productos


//Ruta para formulario crear producto
Route::get('/CreacionP', 'Productos@listaNecesarioParaCreacionProducto');

//Ruta para crear producto
Route::any('Produc/crear', [
    'uses'=>'Productos@store',
    'as'=>'produc.crea'
]);

//Controlador Catalogo de productos
Route::any('/CatalogProduc','Productos@listaProductos')->name('CatalogProduc');


//Ruta para eliminar producto
Route::any('Produc/{id}/destroy', [
    'uses'=>'Productos@destroy',
    'as'=>'produc.destroy'
]);
//Ruta para editar producto
//Ruta para obtener subcategorias
Route::get('/ed/{idP}','Productos@byAll');
Route::any('Produc/{id}/actualizar', [
    'uses'=>'Productos@update',
    'as'=>'produc.actualiza'
]);



Route::resource('Sucursales', 'Sucursales');
Route::any('/BuscarSuc','Sucursales@BuscarSuc')->name('BuscarSuc');



///////////Rutas para lineas y sublineas

//Ruta para crear linea
Route::any('Linea/crear', [
    'uses'=>'LineaSublinea@storeLinea',
    'as'=>'linea.crea'
]);

//Ruta para guardar una sublinea
Route::any('Sublinea/crear', [
    'uses'=>'LineaSublinea@storeSublinea',
    'as'=>'sublinea.crea'
]);

//Ruta para obtener subcategorias
Route::get('/sub/{id}','Productos@byCategoria');


Route::get('/lineas','LineasController@listaCategorias')->name('lineas');


Route::get('clave-sat','Controlador_Sat@verSat')->name('clave-sat');

app/inventario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class inventario extends Model
{
    protected $table = 'inventario';
    protected $primaryKey = 'id_Producto';
    protected $dateFormat = 'Y-m-d H:i:s';
    public $timestamps = false;
    protected $fillable = ['cantidad', 'cantMaxima','cantMin', 'estadoinventario', 'entrada', 'salida', 'idAlmacen', 'id_ubicacion', 'id_Producto', 'bloqueado', 'disponible'];


}

resources/views/Inventario/CatalogoProductosInv.blade.php
@extends('layouts.cabe')
    <!-- /#sidebar-wrapper -->
@section('content')
    <!-- Page Content -->





  <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nombre</th>
      <th scope="col">Clave</th>
      <th scope="col">Marca</th>
      <th scope="col">Proveedor</th>
      <th scope="col">Costo</th>
      <th scope="col">Cantidad</th>
      <th scope="col">Estado</th>
    </tr>
  </thead>
  <tbody>
    @foreach($productos as $producto)
    <tr>
      <th>{!!$producto ->id_Producto!!}</th>
      <td>{!!$producto ->nombre!!}</th>
      <td>{!!$producto ->clave!!}</td>
      <td>{!!$producto ->marca!!}</td>
      <td>{!!$producto ->proveedor!!}</td>
      <td>{!!$producto ->costo!!}</td>
      <td>{!!$producto ->cantidad!!}</td>
      <td>{!!$producto ->descripcion!!}</td>
    </tr>
       @endforeach

  </tbody>
</table>
</div>
      </div>
    </div>
    <!-- /#page-content-wrapper -->
  <!-- /#wrapper -->


@endsection

resources/views/Inventario/Crearmodal.blade.php
     <div class="col-lg-12">
                <form class="form-horizontal" id="store-form"  method="post" role="form" action="{{route('ModInv.store')}}">
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                  {{method_field('POST')}}
                    <div class="row">
                      <input type="hidden" name="id" id="idCr" class="form-control">
                      <div class="form-group col-md-3">
                        <label for="cantidad">Cantidad</label>
                        <input type="number" name="Cantidad" id="CantidadC" class="form-control" placeholder="Cantidad"  value="" style="background-color: white; color:#808B96;" required="required">
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6 ">
                        <label for="cantidadMax">Stock Máximo</label>
                        <input type="text" name="cantidadMax" id="cantidadMaxC" class="form-control" placeholder="Stock Máximo"  value="" required="required">
                      </div>
                      <div class="col-md-6 ">
                        <label for="cantidadMin">Stock Mínimo</label>
                        <input type="text" name="cantidadMin" id="cantidadMinC" class="form-control" placeholder="Stock Mínimo"  value="" required="required">
                      </div>
                    </div>
      </div>

resources/views/Inventario/Editarmodal.blade.php
              <div class="col-lg-12">
                <form class="form-horizontal" id="edit-form"  method="post" role="form" action="{{route('ModInv.update', $producto->id_Producto)}}" onsubmit="return envia(this)">
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                  {{method_field('PUT')}}
                  <!--Datos Generales-->
                  <input type="hidden" name="id" id="id">
                  <input type="hidden" name="usuario" id="usuario" value="{{Auth::user()->id}}">
                  <div class="row">
                      <div class="col-md-3">
                        <label for="id">ID Producto</label>
                        <input type="text" name="id" id="idE" class="form-control" placeholder="ID Producto" value="" readonly="readonly" style="background-color: white; color:#808B96;"><br/>
                    </div>
                    <div class="col-md-3">
                        <label for="Clave">Clave</label>
                        <input type="text" name="Clave" id="ClaveE" class="form-control" placeholder="Clave"  value="" disabled="disabled" style="background-color: white; color:#808B96;"><br/>
                    </div>
                    <div class="col-md-6">
                      <label for="Clavesat">Clave SAT</label>
                      <input type="text" name="Clavesat" id="ClavesatE" class="form-control" placeholder="Clave Sat"  value="" disabled="disabled" style="background-color: white; color:#808B96;"><br/>
                    </div>
                  </div>
                   <div class="form-group">
                    <label for="productname">Nombre de Producto</label>
                    <input type="text" name="productname" id="productnameE" class="form-control" placeholder="Nombre del Producto"  value="" disabled="disabled" style="background-color: white; color:#808B96;">
                  </div>

                  <!--Inventario -->
                    <div class="row">
                      <div class="form-group col-md-3">
                        <label for="entradasE">Entradas</label>
                        <input type="number" name="entrada" id="entradaE" class="form-control" placeholder="Entradas">
                      </div>
                      <div class="form-group col-md-3">
                        <label for="salidasE">Salidas</label>
                        <input type="number" name="salida" id="salidaE" class="form-control" placeholder="Salidas">
                      </div>
                    </div>
                    <div class="row">
                      <div class="form-group col-md-3">
                        <label for="cantidad">Cantidad Total</label>
                        <input type="number" name="CantidadT" id="CantidadET" class="form-control" placeholder="Cantidad" readonly="readonly" value="" style="background-color: white; color:#808B96;">
                      </div>
                      <div class="form-group col-md-3">
                        <label for="cantidad">Cantidad Bloqueada</label>
                        <input type="number" name="CantidadB" id="CantidadEB" class="form-control" placeholder="Cantidad" readonly="readonly" value="" style="background-color: white; color:#808B96;">
                      </div>
                      <div class="form-group col-md-3">
                        <label for="cantidad">Cantidad Disponible</label>
                        <input type="number" name="CantidadD" id="CantidadED" class="form-control" placeholder="Cantidad" readonly="readonly" value="" style="background-color: white; color:#808B96;">
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6 ">
                        <label for="cantidadMax">Stock Máximo</label>
                        <input type="text" name="cantidadMax" id="cantidadMaxE" class="form-control" placeholder="Stock Máximo"  value="">
                      </div>
                      <div class="col-md-6 ">
                        <label for="cantidadMin">Stock Mínimo</label>
                        <input type="text" name="cantidadMin" id="cantidadMinE" class="form-control" placeholder="Stock Mínimo"  value="">
                      </div>
                    </div>
                
              </div>

<!--Para Bloqear los inputs de E/S de productos-->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('#salidaE').val('');

                $('#entradaE').change(function () {
                    var value = $(this).val();
                    if (value.length != 0) {
                        $('#salidaE').val('');
                        $('#salidaE').attr("disabled", true);
                    }
                    else
                        $('#salidaE').removeAttr("disabled");
                });

                $('#salidaE').change(function () {
                    var value = $(this).val();
                    if (value.length != 0) {
                        $('#entradaE').val('');
                        $('#entradaE').attr("disabled", true);
                    }
                    else
                        $('#entradaE').removeAttr("disabled");
                });
            });

            

        </script>
      

resources/views/Inventario/ListaProductos.blade.php
<div class="col-lg-12">
  <form  method="post" id="store-form" action="{{route('ModInv.store')}}" onsubmit="return envia(this)">
                  {{method_field('POST')}}

    <input type="hidden" name="_token" value="{{ csrf_token() }}">              
    <input type="hidden" name="id" id="id">
    <input type="hidden" name="usuario" id="usuario" value="{{Auth::user()->id}}">
	<select class="form-control" id="buscador" onchange="verproduct()">
    <option value="">Selecciona un producto</option>
		@foreach($productosGeneral as $d)
		  <option value="{!!$d->id_Producto!!}">{!!$d->descripcion!!}</option>
		@endforeach
	</select> 
		<div class="row">
                      <div class="col-md-3">
                        <label for="idC">ID Producto</label>
                        <input type="text" name="id" id="idC" class="form-control" placeholder="ID Producto" value="" readonly="readonly" style="background-color: white; color:#808B96;"><br/>
                    </div>
                    <div class="col-md-3">
                        <label for="ClaveC">Clave</label>
                        <input type="text" name="Clave" id="ClaveC" class="form-control" placeholder="Clave"  value="" disabled="disabled" style="background-color: white; color:#808B96;"><br/>
                    </div>
                    <div class="col-md-6">
                      <label for="ClavesatC">Clave SAT</label>
                      <input type="text" name="Clavesat" id="ClavesatC" class="form-control" placeholder="Clave Sat"  value="" disabled="disabled" style="background-color: white; color:#808B96;"><br/>
                    </div>
                  </div>
           <div class="row">
           		<div class="col-md-4">
                        <label for="marcaC">Marca</label>
                        <input type="text" name="marca" id="marcaC" class="form-control" placeholder="ID Producto" value="" readonly="readonly" style="background-color: white; color:#808B96;"><br/>
                    </div>
                    <div class="col-md-6">
                        <label for="proveedorC">Proveedor</label>
                        <input type="text" name="proveedor" id="proveedorC" class="form-control" placeholder="Clave"  value="" disabled="disabled" style="background-color: white; color:#808B96;"><br/>
                    </div>
           </div>
 </div>


 <script type="text/javascript">
   function verproduct(){
var cod = document.getElementById("buscador").value;

  $.ajax({
    url: 'ModN/'+ cod,
    type:'get'
  }).done(function(res){
    console.log(res);
    $('#idC').val(res.datos[0].id_Producto);
    $('#idCr').val(res.datos[0].id_Producto);
    $('#ClaveC').val(res.datos[0].clave);
    $('#ClavesatC').val(res.datos[0].sat);
    $('#marcaC').val(res.datos[0].marca);
    $('#proveedorC').val(res.datos[0].proveedor);
  });
}

 </script>

resources/views/Inventario/ShowModal.blade.php
<div class="col-md-12">
          <div class="panel-body">
              <div>
                <form class="form-horizontal" id="edit-form"  method="post" role="form" action="/ModInv">
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                  <div role="tabpanel" class="tab-pane " id="datosinv">
                  <div class="row">
                    <div class="form-group col-md-3">
                      <label for="entradas">Entradas</label>
                      <input type="number" name="entrada" id="entrada" class="form-control" placeholder="Entradas" disabled="disabled" style="background-color: white; color:#808B96;">
                    </div>
                    <div class="form-group col-md-3">
                      <label for="salidas">Salidas</label>
                      <input type="number" name="salida" id="salida" class="form-control" placeholder="Salidas" disabled="disabled" style="background-color: white; color:#808B96;">
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col-md-3">
                      <label for="cantidad">Cantidad Total</label>
                      <input type="text" name="CantidadT" id="CantidadT" class="form-control" placeholder="Cantidad"  value="" disabled="disabled" style="background-color: white; color:#808B96;">
                    </div>
                    <div class="form-group col-md-3">
                      <label for="cantidad">Cantidad Bloqueada</label>
                      <input type="text" name="Cantidad" id="CantidadB" class="form-control" placeholder="Cantidad"  value="" disabled="disabled" style="background-color: white; color:#808B96;">
                    </div>
                    <div class="form-group col-md-3">
                      <label for="cantidad">Cantidad Disponible</label>
                      <input type="text" name="Cantidad" id="CantidadD" class="form-control" placeholder="Cantidad"  value="" disabled="disabled" style="background-color: white; color:#808B96;">
                    </div>
                  </div>
                  <div class="row">
                  <div class="col-md-6 ">
                    <label for="cantidadMax">Stock Máximo</label>
                    <input type="text" name="cantidadMax" id="cantidadMax" class="form-control" placeholder="Stock Máximo" disabled="disabled" style="background-color: white; color:#808B96;">
                  </div>

                  <div class="col-md-6 ">
                    <label for="cantidadMin">Stock Mínimo</label>
                    <input type="text" name="cantidadMin" id="cantidadMin" class="form-control" placeholder="Stock Mínimo" disabled="disabled" style="background-color: white; color:#808B96;">
                  </div>
                  </div>
                </div>
                </form>
              </div>
      </div>
    </div>
      

resources/views/Inventario/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>

 <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nombre</th>
      <th scope="col">Clave</th>
      <th scope="col">Marca</th>
      <th scope="col">Proveedor</th>
      <th scope="col">Costo</th>
      <th scope="col">Cantidad</th>
      <th scope="col">Estado</th>
      <th scope = "col" style="padding: 0;">Opciones </th>
    </tr>
  </thead>
  <tbody>
    @foreach($datos as $producto)
    <tr>
      <th>{!!$producto ->id_Producto!!}</th>
      <td>{!!$producto ->nombre!!}</th>
      <td>{!!$producto ->clave!!}</td>
      <td>{!!$producto ->marca!!}</td>
      <td>{!!$producto ->proveedor!!}</td>
      <td>{!!$producto ->costo!!}</td>
      <td>{!!$producto ->cantidad!!}</td>
      <td>{!!$producto ->descripcion!!}</td>
      <td style="padding: 0;">
            <a href="{{route('modificar',$producto->id_Producto)}}"><input type="submit" name="register-submit" id="register-submit" tabindex="4" class="btn btn-outline-success my-1 my-sm-0" value="Modificar"></a>

            <a href="{{route('eliminar',$producto->id_Producto)}}"><input type="submit" name="register-submit" id="register-submit" tabindex="4" class="btn btn-outline-danger my-1 my-sm-0 openBtn" value="Eliminar"></a>
       </td>
    </tr>
       @endforeach

  </tbody>
</table>
</body>
</html>